import { NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
export class ScholarshipApplication {
    constructor(
        public FatherName: string = '',
        public MotherName: string = '',
        public Religion: string = '',
        public Community: string = '',
        public AadharNumber: string = '',
        public FamilyAnnualIncome: string = '',
        public InstituteName: string = '',
        public PresentCourse: string = '',
        public PresentCourseYear: string = '',
        public ModeOfStudy: string = '',
        public UniversityBoardName: string = '',
        public ClassStartDate: string = '',
        public PreviousCourse: string = '',
        public PreviousPassingYear: string = '',
        public PreviousClassPercentage: string = '',
        public RollNumber: string = '',
        public BoardName: string = '',
        public PassingYear: string = '',
        public PercentageObtained: string = '',
        public Rollnumber: string = '',
        public Boardname: string = '',
        public Passingyear: string = '',
        public Percentageobtained: string = '',
        public AddmissionFee: string = '',
        public TutionFee: string = '',
        public OtherFee: string = '',
        public IsDisabled: string = '',
        public TypeOfDisability: string = '',
        public DisabilityPercentage: string = '',
        public MartialStatus: string = '',
        public ParentsProfession: string = '',
        public State: string = '',
        public District: string = '',
        public BlockTaluk: string = '',
        public HouseNumber: string = '',
        public StreetNumber: string = '',
        public Pincode: string = '',
        public ChooseScheme: string = '',
        public DomicileCertificate: string = '',
        public StudentPhotograph: string = '',
        public InstituteIDCard: string = '',
        public CasteIncomeCertificate: string = '',
        public PreviousYearMarksheet: string = '',
        public FeeReceiptofCurrentYear: string = '',
        public BankPassbook: string = '',
        public AadharCard: string = '',
        public ClassMarksheet: string = '',
        public Classmarksheet: string = '',
        public tickisrequired: boolean = false

    ) {}
}
